-- V0__initial_schema.sql
-- Schema base completo de la aplicación
-- Crea todas las tablas y secuencias base sobre las que los V1-V5 aplican cambios

-- ─── SECUENCIAS (Hibernate legacy allocationSize=50) ─────────────────────────

CREATE SEQUENCE IF NOT EXISTS public.article_media_seq   START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.article_seq         START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.comment_seq         START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.comment_reaction_seq START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.content_seq         START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.event_category_seq  START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.event_invitation_seq START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.event_media_seq     START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.event_registration_seq START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.event_seq           START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.institution_seq     START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.link_seq            START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.media_seq           START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.nav_item_seq        START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.post_reaction_seq   START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.post_seq            START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.section_seq         START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.social_network_seq  START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.text_seq            START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;

-- ─── TABLAS GLOBALES (sin tenant) ────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.role (
    id_role bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    character varying(255)
);

CREATE TABLE IF NOT EXISTS public.permissions (
    id_permission bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_permission character varying(255)
);

CREATE TABLE IF NOT EXISTS public.rol_permissions (
    permission_id bigint NOT NULL,
    role_id       bigint NOT NULL,
    PRIMARY KEY (permission_id, role_id)
);

CREATE TABLE IF NOT EXISTS public.comment_config (
    id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid               character varying(36)  NOT NULL UNIQUE,
    configuration_type character varying(50)  NOT NULL,
    name               character varying(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.emoji_type (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       character varying(36) NOT NULL UNIQUE,
    emoji_code character varying(5)  NOT NULL,
    emoji_name character varying(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.event_category (
    id               integer NOT NULL PRIMARY KEY,
    is_active        boolean NOT NULL,
    color            character varying(7),
    created_date     timestamp(6) without time zone,
    last_modified_date timestamp(6) without time zone,
    uuid             character varying(36) NOT NULL UNIQUE,
    icon             character varying(50),
    name             character varying(100) NOT NULL,
    description      character varying(500)
);

CREATE TABLE IF NOT EXISTS public.invalid_token (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invalidated_at timestamp(6) without time zone,
    token          character varying(255)
);

CREATE TABLE IF NOT EXISTS public.document_file (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status       character varying(20)  NOT NULL,
    type         character varying(20)  NOT NULL,
    uuid         character varying(36)  NOT NULL UNIQUE,
    name         character varying(100) NOT NULL,
    url_resource character varying(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.image_file (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status       character varying(20)  NOT NULL,
    type         character varying(20)  NOT NULL,
    uuid         character varying(36)  NOT NULL UNIQUE,
    name         character varying(100) NOT NULL,
    url_resource character varying(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.video_file (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status       character varying(20)  NOT NULL,
    type         character varying(20)  NOT NULL,
    uuid         character varying(36)  NOT NULL UNIQUE,
    name         character varying(100) NOT NULL,
    url_resource character varying(200) NOT NULL
);

-- ─── TABLAS TENANT ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.institution (
    id                 integer NOT NULL PRIMARY KEY,
    deleted            boolean DEFAULT false NOT NULL,
    created_date       timestamp(6) without time zone,
    last_modified_date timestamp(6) without time zone,
    uuid               character varying(36)  NOT NULL UNIQUE,
    name               character varying(150) NOT NULL,
    description        character varying(300) NOT NULL,
    location           character varying(300) NOT NULL,
    category           character varying(100) NOT NULL,
    email              character varying(80)  NOT NULL,
    phone              character varying(20)  NOT NULL,
    url                character varying(80)  NOT NULL,
    logo_url           character varying(100) NOT NULL,
    background_url     character varying(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.users (
    id_user            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid               character varying(36) NOT NULL UNIQUE,
    email              character varying(50) NOT NULL UNIQUE,
    name               character varying(50) NOT NULL,
    last_name          character varying(80) NOT NULL,
    password           character varying(80) NOT NULL,
    phone              character varying(15),
    photo_cover_path   character varying(100),
    photo_profile_path character varying(100)
);

CREATE TABLE IF NOT EXISTS public.user_roles (
    user_id integer NOT NULL,
    role_id bigint  NOT NULL,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS public.token (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_revoked boolean NOT NULL,
    user_id    integer NOT NULL,
    token      character varying(2048) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.nav_item (
    id                 integer NOT NULL PRIMARY KEY,
    deleted            boolean DEFAULT false NOT NULL,
    visible            boolean DEFAULT true NOT NULL,
    item_order         integer NOT NULL,
    created_date       timestamp(6) without time zone,
    last_modified_date timestamp(6) without time zone,
    uuid               character varying(36)  NOT NULL UNIQUE,
    institution_id     character varying(36),
    user_id            character varying(36),
    label              character varying(200) NOT NULL,
    url                character varying(1000)
);

CREATE TABLE IF NOT EXISTS public.section (
    id                 integer NOT NULL PRIMARY KEY,
    deleted            boolean DEFAULT false NOT NULL,
    created_date       timestamp(6) without time zone,
    date               timestamp(6) without time zone NOT NULL,
    last_modified_date timestamp(6) without time zone,
    uuid               character varying(36)  NOT NULL UNIQUE,
    institution_id     character varying(36)  NOT NULL,
    nav_item_id        character varying(36),
    user_id            character varying(36)  NOT NULL,
    name               character varying(1000) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.social_network (
    id                 integer NOT NULL PRIMARY KEY,
    created_date       timestamp(6) without time zone,
    last_modified_date timestamp(6) without time zone,
    uuid               character varying(36) NOT NULL UNIQUE,
    institution_id     character varying(36) NOT NULL,
    name               character varying(50)  NOT NULL,
    link               character varying(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.followers (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution_id integer NOT NULL,
    user_id        integer NOT NULL,
    followed_since timestamp(6) without time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS public.content (
    id                 integer NOT NULL PRIMARY KEY,
    created_date       timestamp(6) without time zone,
    last_modified_date timestamp(6) without time zone,
    uuid               character varying(36) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.text (
    id                 integer NOT NULL PRIMARY KEY,
    created_date       timestamp(6) without time zone,
    last_modified_date timestamp(6) without time zone,
    uuid               character varying(36) NOT NULL UNIQUE,
    content_id         character varying(36),
    text               character varying(1200) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.media (
    id                 integer NOT NULL PRIMARY KEY,
    number             integer NOT NULL,
    created_date       timestamp(6) without time zone,
    last_modified_date timestamp(6) without time zone,
    uuid               character varying(36)  NOT NULL UNIQUE,
    file_type          character varying(10)  NOT NULL,
    file_path          character varying(100) NOT NULL,
    file_name          character varying(150) NOT NULL,
    content_id         character varying(36)
);

CREATE TABLE IF NOT EXISTS public.post (
    id                 integer NOT NULL PRIMARY KEY,
    deleted            boolean DEFAULT false NOT NULL,
    created_date       timestamp(6) without time zone,
    last_modified_date timestamp(6) without time zone,
    post_date          timestamp(6) without time zone NOT NULL,
    uuid               character varying(36) NOT NULL UNIQUE,
    post_type          character varying(255) NOT NULL,
    institution_id     character varying(36) NOT NULL,
    user_id            character varying(36) NOT NULL,
    content_id         character varying(36) NOT NULL,
    comment_config_id  character varying(36) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.post_group (
    post_id  character varying(36) NOT NULL,
    group_id character varying(36) NOT NULL,
    PRIMARY KEY (post_id, group_id)
);

CREATE TABLE IF NOT EXISTS public.post_reaction (
    id                 integer NOT NULL PRIMARY KEY,
    deleted            boolean DEFAULT false NOT NULL,
    created_date       timestamp(6) without time zone,
    last_modified_date timestamp(6) without time zone,
    reaction_date      timestamp(6) without time zone NOT NULL,
    uuid               character varying(36) NOT NULL UNIQUE,
    post_id            character varying(36) NOT NULL,
    user_id            character varying(36) NOT NULL,
    emoji_type_id      character varying(36) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.groups (
    id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid   character varying(36) NOT NULL UNIQUE,
    name   character varying(50) NOT NULL,
    status character varying(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.comment (
    id                 integer NOT NULL PRIMARY KEY,
    moderated          boolean NOT NULL,
    post_id            integer NOT NULL,
    user_id            integer NOT NULL,
    comment_date       timestamp(6) without time zone NOT NULL,
    created_date       timestamp(6) without time zone,
    last_modified_date timestamp(6) without time zone,
    uuid               character varying(36)  NOT NULL UNIQUE,
    content            character varying(255) NOT NULL,
    state              character varying(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.comment_reaction (
    id                 integer NOT NULL PRIMARY KEY,
    deleted            boolean DEFAULT false NOT NULL,
    created_date       timestamp(6) without time zone,
    last_modified_date timestamp(6) without time zone,
    reaction_date      timestamp(6) without time zone NOT NULL,
    uuid               character varying(36) NOT NULL UNIQUE,
    comment_id         character varying(36) NOT NULL,
    user_id            character varying(36) NOT NULL,
    emoji_type_id      character varying(36) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.replies (
    reply_id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id     integer NOT NULL,
    parent_reply_id integer,
    user_id        integer NOT NULL,
    created_at     timestamp(6) with time zone NOT NULL,
    uuid           character varying(36)  NOT NULL UNIQUE,
    content        character varying(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.reply_reactions (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reply_id      integer NOT NULL,
    user_id       integer NOT NULL,
    emoji_type_id integer NOT NULL,
    reaction_date timestamp(6) without time zone,
    uuid          character varying(36) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.article (
    id                 integer NOT NULL PRIMARY KEY,
    deleted            boolean DEFAULT false NOT NULL,
    created_date       timestamp(6) without time zone,
    date               timestamp(6) without time zone,
    last_modified_date timestamp(6) without time zone,
    uuid               character varying(36) UNIQUE,
    section_id         character varying(36),
    user_id            character varying(36),
    title              character varying(1000),
    text               character varying(3000)
);

CREATE TABLE IF NOT EXISTS public.article_media (
    id                 integer NOT NULL PRIMARY KEY,
    deleted            boolean DEFAULT false NOT NULL,
    number             integer NOT NULL,
    created_date       timestamp(6) without time zone,
    last_modified_date timestamp(6) without time zone,
    uuid               character varying(36)  NOT NULL UNIQUE,
    file_type          character varying(30)  NOT NULL,
    file_name          character varying(150) NOT NULL,
    file_path          character varying(150) NOT NULL,
    article_id         character varying(36)
);

CREATE TABLE IF NOT EXISTS public.link (
    id                 integer NOT NULL PRIMARY KEY,
    deleted            boolean DEFAULT false NOT NULL,
    created_date       timestamp(6) without time zone,
    last_modified_date timestamp(6) without time zone,
    uuid               character varying(36) NOT NULL UNIQUE,
    owner_uuid         character varying(36),
    owner_type         character varying(50),
    name               character varying(150) NOT NULL,
    url                character varying(500) NOT NULL,
    CONSTRAINT link_owner_type_check CHECK (owner_type IN ('ARTICLE','POST','INSTITUTION','USER'))
);

CREATE TABLE IF NOT EXISTS public.event (
    id                   integer NOT NULL PRIMARY KEY,
    deleted              boolean DEFAULT false NOT NULL,
    is_public            boolean NOT NULL,
    max_capacity         integer NOT NULL,
    requires_registration boolean NOT NULL,
    created_date         timestamp(6) without time zone,
    end_date             timestamp(6) without time zone,
    last_modified_date   timestamp(6) without time zone,
    start_date           timestamp(6) without time zone NOT NULL,
    uuid                 character varying(36)   NOT NULL UNIQUE,
    status               character varying(20),
    user_id              character varying(36)   NOT NULL,
    cover_image_path     character varying(100),
    title                character varying(200)  NOT NULL,
    location             character varying(500),
    description          character varying(2000)
);

CREATE TABLE IF NOT EXISTS public.event_invitation (
    id                 integer NOT NULL PRIMARY KEY,
    deleted            boolean DEFAULT false NOT NULL,
    email_sent         boolean NOT NULL,
    created_date       timestamp(6) without time zone,
    email_sent_date    timestamp(6) without time zone,
    expiration_date    timestamp(6) without time zone,
    invitation_date    timestamp(6) without time zone NOT NULL,
    last_modified_date timestamp(6) without time zone,
    response_date      timestamp(6) without time zone,
    uuid               character varying(36)  NOT NULL UNIQUE,
    status             character varying(20),
    event_id           character varying(36)  NOT NULL,
    invited_user_id    character varying(36)  NOT NULL,
    inviter_user_id    character varying(36)  NOT NULL,
    invitation_token   character varying(100),
    personal_message   character varying(500)
);

CREATE TABLE IF NOT EXISTS public.event_media (
    id                 integer NOT NULL PRIMARY KEY,
    deleted            boolean DEFAULT false NOT NULL,
    display_order      integer NOT NULL,
    is_cover           boolean NOT NULL,
    is_public          boolean NOT NULL,
    created_date       timestamp(6) without time zone,
    file_size          bigint NOT NULL,
    last_modified_date timestamp(6) without time zone,
    uuid               character varying(36)  NOT NULL UNIQUE,
    event_id           character varying(36)  NOT NULL,
    file_type          character varying(50)  NOT NULL,
    mime_type          character varying(50)  NOT NULL,
    file_name          character varying(150) NOT NULL,
    alt_text           character varying(200),
    file_path          character varying(200) NOT NULL,
    description        character varying(500)
);

CREATE TABLE IF NOT EXISTS public.event_registration (
    id                       integer NOT NULL PRIMARY KEY,
    deleted                  boolean DEFAULT false NOT NULL,
    email_notification_sent  boolean NOT NULL,
    reminder_sent            boolean NOT NULL,
    created_date             timestamp(6) without time zone,
    last_modified_date       timestamp(6) without time zone,
    registration_date        timestamp(6) without time zone NOT NULL,
    uuid                     character varying(36)  NOT NULL UNIQUE,
    status                   character varying(20),
    event_id                 character varying(36)  NOT NULL,
    user_id                  character varying(36)  NOT NULL,
    confirmation_code        character varying(100)
);
