-- V6__create_uploaded_file.sql
-- Unifica image_file, video_file y document_file en una sola tabla uploaded_file.
-- Las tablas antiguas se mantienen hasta que la Fase 2 (FK en media/article_media) esté completa.

CREATE TABLE IF NOT EXISTS public.uploaded_file (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid         character varying(36)  NOT NULL UNIQUE,
    name         character varying(100) NOT NULL,
    url_resource character varying(200) NOT NULL,
    category     character varying(20)  NOT NULL,
    mime_type    character varying(50)  NOT NULL,
    status       character varying(20)  NOT NULL
);

-- Migrar datos existentes de las tres tablas redundantes
INSERT INTO public.uploaded_file (uuid, name, url_resource, category, mime_type, status)
SELECT uuid, name, url_resource, 'IMAGE', type, status
FROM public.image_file
ON CONFLICT (uuid) DO NOTHING;

INSERT INTO public.uploaded_file (uuid, name, url_resource, category, mime_type, status)
SELECT uuid, name, url_resource, 'VIDEO', type, status
FROM public.video_file
ON CONFLICT (uuid) DO NOTHING;

INSERT INTO public.uploaded_file (uuid, name, url_resource, category, mime_type, status)
SELECT uuid, name, url_resource, 'DOCUMENT', type, status
FROM public.document_file
ON CONFLICT (uuid) DO NOTHING;
